<?php
putenv("NOMEDOBANCO_MYSQL_HOST=");
putenv("NOMEDOBANCO_MYSQL_DBNAME=");
putenv("NOMEDOBANCO_MYSQL_USER=");
putenv("NOMEDOBANCO_MYSQL_PASSWORD=");
putenv("NOMEDOBANCO_MYSQL_PORT=");
putenv('JWT_SECRET_KEY=');