<?php
putenv("NOMEDOBANCO_MYSQL_HOST=localhost");
putenv("NOMEDOBANCO_MYSQL_DBNAME=loja");
putenv("NOMEDOBANCO_MYSQL_USER=root");
putenv("NOMEDOBANCO_MYSQL_PASSWORD=");
putenv("NOMEDOBANCO_MYSQL_PORT=3306");
//putenv('JWT_SECRET_KEY=');